baseURL = "https://ykcab.github.io/N2x-B4x_BMW_Wiki/"
title = "BMW N2x & B4x Engine Wiki"
description = "Comprehensive documentation for BMW N20, N26, B46 and B48 engines"
languageCode = "en-us"

# Theme settings
theme = "ace-documentation"
enableGitInfo = true

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Useful when translating
enableMissingTranslationPlaceholders = true

# Enable search
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]

# Configure how URLs look
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration
[languages]
[languages.en]
title = "BMW N2x & B4x Engine Wiki"
languageName = "English"
weight = 1
[languages.en.params]
description = "Comprehensive documentation for BMW N20, N26, B46 and B48 engines"

# Site Parameters
[params]
copyright = "The BMW Engine Wiki Contributors"
privacy_policy = "https://github.com/ykcab/N2x-B4x_BMW_Wiki"
disable_search = false
use_cdn = true
googleAnalytics = ""  # Disable Google Analytics

# Repository configuration
github_repo = "https://github.com/ykcab/N2x-B4x_BMW_Wiki"
github_repository = "https://github.com/ykcab/N2x-B4x_Wiki"
github_doc_repository = "https://github.com/ykcab/N2x-B4x_Wiki"
github_branch = "main"
github_doc_branch = "main"

# Search configuration
algolia_docsearch = false
offlineSearch = true
search_minify = true

# UI configuration
menu_style = "slide-menu"
dateformat = "Jan 2, 2006"

# Syntax highlighting
prism_syntax_highlighting = true

# Dependencies
[params.dependencies]
bootstrap = "4.6.2"
fontawesome = "6.4.2"

# User interface configuration
[params.ui]
sidebar_search_disable = false
version_menu = "Releases"
navbar_logo = true
sidebar_menu_compact = true
breadcrumb_disable = false
sidebar_menu_foldable = true
ul_show = 1
footer_about_enable = true

# Feedback configuration
[params.ui.feedback]
enable = true
yes = 'Glad to hear it! Please <a href="https://github.com/ykcab/N2x-B4x_Wiki/issues/new"> tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/ykcab/N2x-B4x_Wiki/issues/new"> tell us how we can improve</a>.'

# Reading time configuration
[params.ui.readingtime]
enable = true

[params.time]
enable = true

# Links configuration
[params.links]
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/ykcab/N2x-B4x_Wiki"
icon = "fab fa-github"
desc = "Development takes place here!"

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Documentation"
url = "/docs"
weight = 2

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = true
