baseURL = "/"
title = "BMW N20 & B48 Engine Wiki"
description = "Comprehensive documentation for BMW N20 and B48 engines"
languageCode = "en-us"

# Theme settings
theme = ["docsy"]
enableGitInfo = true

# Docsy theme settings
[module]
  proxy = "direct"
  # uncomment line below if you want to make a local copy
  # replacements = "github.com/google/docsy -> ../../docsy"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Useful when translating
enableMissingTranslationPlaceholders = true

# Enable search
[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML" ]

# Configure how URLs look
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking
# id = "UA-00000000-0"

# Language configuration
[languages]
[languages.en]
title = "BMW N20 & B48 Engine Wiki"
description = "Comprehensive documentation for BMW N20 and B48 engines"
languageName = "English"
weight = 1

# Everything below this are Site Params
[params]
copyright = "The BMW Engine Wiki Contributors"
privacy_policy = "https://policies.google.com/privacy"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/yourusername/BMW-N2x-B4x-Wiki"
github_branch = "main"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable search
sidebar_search_disable = false
# Enable the doc versions selector
version_menu = "Releases"
navbar_logo = true
sidebar_menu_compact = true
breadcrumb_disable = false
sidebar_menu_foldable = true
ul_show = 1
footer_about_enable = true # Set to false to disable the About block within the footer

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/yourusername/BMW-N2x-B4x-Wiki/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/yourusername/BMW-N2x-B4x-Wiki/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
[params.ui.readingtime]
enable = true

# Adds a reading time to the top of each doc
[params.time]
enable = true

# SEO Configuration
[params.links]
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/yourusername/BMW-N2x-B4x-Wiki"
icon = "fab fa-github"
desc = "Development takes place here!"

# Navigation
# [[menu.main]]
# name = "Documentation"
# weight = 20
# url = "/docs/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    guessSyntax = true
